### ISSUE TITLE
Deepspeed finetuning for Llama2

### ISSUE THREAD

**Issue by TahaBinhuraib** [databricks/databricks-ml-examples#45]
Is the python file in its final form? I just looked at the code, and don't think that the script is doing anything more than inference, am I missing something?

**Comment by es94129** [comment]
The file [05_fine_tune_deepspeed.py](https://github.com/databricks/databricks-ml-examples/blob/master/llm-models/llamav2/llamav2-7b/05_fine_tune_deepspeed.py) is a notebook, where in one of the cells it runs
```sh
deepspeed --num_gpus=4 scripts/fine_tune_deepspeed.py
```
which runs [this Python script that contains training code](https://github.com/databricks/databricks-ml-examples/blob/master/llm-models/llamav2/llamav2-7b/scripts/fine_tune_deepspeed.py).

**Comment by TahaBinhuraib** [comment]
Thanks 🙏
