### ISSUE TITLE
Use a newer commit hash for Llama-2-7b-chat-hf

### ISSUE THREAD

**Issue by andrewshieh** [databricks/databricks-ml-examples#70]
https://github.com/databricks/databricks-ml-examples/blob/299fec3115d67fc03faa10764ab99be69f4e582d/llm-models/llamav2/llamav2-7b/02_mlflow_logging_inference.py#L35C54-L35C54

The [currently referenced commit hash](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/tree/0ede8dd71e923db6258295621d817ca8714516d4) has 3 `bin` files that total ~25Gb, which shouldn't be the case for llama-7b (this is more similar to a llama-13b size). This is also misleading to customers using model serving, when container build and model load takes longer than expected. This commit hash could be [updated to a more recent version](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/tree/main) that has fewer artifacts, that total ~13Gb instead.

**Comment by es94129** [comment]
Thanks for reporting! Fixed in #71.
