### ISSUE TITLE
Llama2-70b MLflow_logging_inference - issue with predict function

### ISSUE THREAD

**Issue by EzekielChukwujindu** [databricks/databricks-ml-examples#97]
The predict function here 
.....................................
        for i in range(len(model_input)):
            prompt = model_input["prompt"][i]
            temperature = model_input.get("temperature", [1.0])[i]
            max_new_tokens = model_input.get("max_new_tokens", [100])[i]

            outputs.append(self._generate_response(prompt, temperature, max_new_tokens))
 .....................................................................
Probably giving IndexError.
Maybe this '        for i in range(len(model_input)):' should be "        for i in range(len(model_input["prompt"])):"

**Comment by EzekielChukwujindu** [comment]
And thank you so much for the repo. Really awesome

**Comment by es94129** [comment]
Hi! I just updated the script for Llama 2 70B to replace the `mlflow.pyfunc.log_model` code with `mlflow.transformers.log_model` that no longer uses the `mlflow.pyfunc.PythonModel` class that you referred to.
